language: python
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements.txt
env:
  - DB=postgresql://localhost:5432/travis_ci_test
services:
  - postgresql
before_script:
  - psql -c "create database travis_ci_test OWNER $USER;" -U postgres
  - alembic upgrade head
script:
  - python -m unittest
