"""Init

Revision ID: f8d6767fbfad
Revises: 
Create Date: 2017-02-20 12:04:27.471776

"""

# revision identifiers, used by Alembic.
revision = 'f8d6767fbfad'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('is_white', sa.Boolean(), nullable=False),
    sa.Column('row', sa.SmallInteger(), nullable=True),
    sa.Column('column', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.CHAR(length=2), nullable=False),
    sa.Column('dst', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn')
    op.drop_table('figure')
    ### end Alembic commands ###
