"""Add Game.fen

Revision ID: 7944fc63556e
Revises: 7531e9589adb
Create Date: 2017-02-27 12:01:26.466591

"""

# revision identifiers, used by Alembic.
revision = '7944fc63556e'
down_revision = '7531e9589adb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('fen', sa.String(length=1000), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'fen')
    ### end Alembic commands ###
