"""Add Game

Revision ID: 7531e9589adb
Revises: f8d6767fbfad
Create Date: 2017-02-20 12:36:28.470094

"""

# revision identifiers, used by Alembic.
revision = '7531e9589adb'
down_revision = 'f8d6767fbfad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('turn', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'turn', 'game', ['game_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turn', type_='foreignkey')
    op.drop_column('turn', 'game_id')
    op.drop_table('game')
    ### end Alembic commands ###
